### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by xxlxsyhl** [sccbhxc/MonteCarloPathTracer#1]
您好，请问您的代码里面intersection是怎么求出来的？我找了好久没有找到
`Color3f PathTracer::trace(Ray& ray, int cur_depth)
{
    Intersection intersection;

    bool is_intersected = pScene->intersect(ray, intersection);

    if (!is_intersected) return BLACK;//递归在ray与pScene无相交结束
    else
    {
        Material& material = intersection.pGeometry->material;
    ‘’‘’‘’‘’‘
}`
进入 pScene->intersect(ray, intersection)
`bool Scene::intersect(Ray& ray, Intersection& intersection)
{
    return kdTree.intersect(ray, intersection);
}`

然后进入kdTree.intersect(ray, intersection)

`{
if (!box.intersect(ray, intersection)) return false;
    bool hit = false;
    if (ray.direction.num[split_axis] >= 0)//ray方向为正方向
    {
        //递归求交
        if (low != NULL) hit |= low->intersect(ray, intersection);
        if (high != NULL) hit |= high->intersect(ray, intersection);
    }
    else
    {
        if (high != NULL) hit |= high->intersect(ray, intersection);
        if (low != NULL) hit |= low->intersect(ray, intersection);
    }
    return hit;
}`

再进入box.intersect(ray, intersection)函数

`bool AABB::intersect(Ray& ray, Intersection& result)
{
    Vec3f& inverseDirection = ray.getInverseDirection();

    float t1 = (low.x - ray.origin.x)*inverseDirection.x;//与box的yoz平面相交，x较小
    float t2 = (high.x - ray.origin.x)*inverseDirection.x;

    float t3 = (low.y - ray.origin.y)*inverseDirection.y;//与box的xoz平面相交，y较小
    float t4 = (high.y - ray.origin.y)*inverseDirection.y;

    float t5 = (low.z - ray.origin.z)*inverseDirection.z;//与box的xoy平面相交，z较小
    float t6 = (high.z - ray.origin.z)*inverseDirection.z;

    //与立体box的前后2个交点的距离t
    float tmin = max(max(min(t1, t2), min(t3, t4)), min(t5, t6));
    float tmax = min(min(max(t1, t2), max(t3, t4)), max(t5, t6));

    // if tmax < 0, ray (line) is intersecting AABB, but whole AABB is behing us
    if (tmax < 0) return false;

    // if tmin > tmax, ray doesn't intersect AABB
	if (tmin > tmax) return false;

    //！！！很关键，可能因为没有交点而t太大；也可能因为浮点误差，与自己相交而太小
    return (tmin < ray.getUpperBound() && tmax > ray.getLowerBound());
    //return true;
}`

里面就没有修改result的语句。Release模式下，提示reslut被优化掉了，再Debug模式下发现是再递归返回的时候intersection被附上值了，但找不到这个交点到底是怎么求出来的？

**Comment by sccbhxc** [comment]
需要注意以下几点：
1. Geometry类是Triangle、Model和KdTree的基类；
2. 另外一个重要的内容是KdTree的构建，看KdTree.cpp中的build(...)函数
```
low = lowVec.size() > 0 ? new KdTree(lowVec, (split_axis + 1) % 3) : NULL;
high = highVec.size() > 0 ? new KdTree(highVec, (split_axis + 1) % 3) : NULL;
```
注意low和high又递归调用了KdTree的构造函数，low和high是KdTree的实例指针，也就是树里面的子树，不断递归构建成了一棵完整的kdtree。
另外一点要格外注意的是
```
    if (length == 1) {
        low = geometry_list[0];
        high = NULL;
        box = low->getAABB();
    }
    else if (length == 2) {
        low = geometry_list[0];
        high = geometry_list[1];
        box = AABB::merge(low->getAABB(), high->getAABB());
    }
```
low和high同样可以是Triangle的实例指针，因为low和high使用了KdTree和Triangle的共同基类Geometry指针类型声明的，实现了类多态性的动态联翩，也就是说Triangle的实例是KdTree中的叶子结点。
总结一下：最大的那个KdTree实例是把一系列小的KdTree实例作为中间的树结点构成的二叉树，最后又把Triangle的实例作为叶子结点，总体上是一棵Geometry指针构成的二叉树；
3. kdTree构造的过程中对应层次的KdTree实例和Triangle实例都有AABB(包围框)， 求交就是先与对应层次的AABB进行求交，判断是否有必要进一步到下一个层次继续求交（如果与AABB都没有交点，那么必定与场景没有交点，没有必要再进一步求交），如果最终光线与Scene有交点，那么会一直求交到叶子结点，也就是与Triangle实例求交，得到最终的交点，对应代码如下(KdTree.cpp中intersect(Ray& ray, Intersection& intersection)函数)：
```
       //递归求交
        if (low != NULL) hit |= low->intersect(ray, intersection);
        if (high != NULL) hit |= high->intersect(ray, intersection);
```
先与中间的KdTree实例求交（递归调用KdTree::intersect(...)），最终与叶子结点上的Triangle实例求交（调用Triangle::intersect(...)），得到最终的交点。函数是通过引用进行传参的(赋值给输入的地方)（intersect(Ray& ray, Intersection& intersection)中的Intersection&是引用，如果不清楚引用是什么，你再额外去看一下C++的引用传参，这里就不写了）。
